<div style="width:520px;border:1px solid #ccc;margin:0 auto;min-height:300px;padding:20px;background-color:#ffffff"><div class="adM">
</div><p style="text-align:center"><a href="https://www.whogohost.com" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.whogohost.com&amp;source=gmail&amp;ust=1561259409803000&amp;usg=AFQjCNF5D7vvzTFK7FQ8tCnbDvFoT_GfgA"><img src="https://ci3.googleusercontent.com/proxy/xKy6gQ8uW8XXrH2gi15slBuKMgF0TZMl9UKZALI6PTFdUk-EGotW6sJooNt4kB_Mjjffb64ma3W_3aSD=s0-d-e1-ft#https://www.whogohost.com/images/logo.png" alt="WhoGoHost" class="CToWUd" border="0"></a></p>
<p>Emerald Developer (Starcom Adavance Emerald Enterprise),</p>
<p>Thank you for contacting our support team. A support ticket has now been opened for your request.</p>
<p>You will be notified when a response is made by email. The details of your ticket are shown below.</p>
<p>Subject: Payment for <a href="http://belbecstore.com" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://belbecstore.com&amp;source=gmail&amp;ust=1561259409803000&amp;usg=AFQjCNFnQi_3crYwDfpBvRS_Pwuy2fG6rg">belbecstore.com</a> with hosting 9,900<br> Priority: Medium<br> Status: <span style="color:#779500">Open</span></p>
<p>You can view the ticket at any time at <a href="https://www.whogohost.com/host/viewticket.php?tid=AEJ-853-48318&amp;c=7Rtmamb7" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.whogohost.com/host/viewticket.php?tid%3DAEJ-853-48318%26c%3D7Rtmamb7&amp;source=gmail&amp;ust=1561259409803000&amp;usg=AFQjCNEro454Ln329zTL9C1Bpe4izwAFpA">https://www.<span class="il">whogohost</span>.com/<wbr>host/viewticket.php?tid=AEJ-<wbr>853-48318&amp;c=7Rtmamb7</a></p>
<p>---<br>
<span class="il">WhoGoHost</span><br>
<br>
<span class="il">Whogohost</span> BizGrowth gives your growing business a unique, yet affordable online presence to help you grow your business and expose you to a wider range of customers.<br>
<br>
Visit <a href="http://www.whogohost.com/bizgrowth/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://www.whogohost.com/bizgrowth/&amp;source=gmail&amp;ust=1561259409803000&amp;usg=AFQjCNGLbebfrVSuTkW75-k3cnxHhdV3Gg">http://www.<span class="il">whogohost</span>.com/<wbr>bizgrowth/</a> to get started at unbeatable prices.<br>
<br>
- Buy your domains for as low as N1,500 only from <span class="il">WhoGoHost</span>! Visit <a href="https://www.whogohost.com/domains/domain-registration.php" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.whogohost.com/domains/domain-registration.php&amp;source=gmail&amp;ust=1561259409803000&amp;usg=AFQjCNE1QB0-377j9g_QhhjlfBPqJ1T9Xg">https://www.<span class="il">whogohost</span>.com/<wbr>domains/domain-registration.<wbr>php</a> for all domain extensions available for purchase.<br>
- Secure your site using SSL and SiteLock. Visit <a href="https://www.whogohost.com/security/ssl.php" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.whogohost.com/security/ssl.php&amp;source=gmail&amp;ust=1561259409803000&amp;usg=AFQjCNGQaBBbdnPp99kjoAJQOBorulzcMw">https://www.<span class="il">whogohost</span>.com/<wbr>security/ssl.php</a> and <a href="https://www.whogohost.com/security/sitelock.php" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.whogohost.com/security/sitelock.php&amp;source=gmail&amp;ust=1561259409804000&amp;usg=AFQjCNHVVgXm-apL4YmLbeXhgo7QtJu03w">https://www.<span class="il">whogohost</span>.com/<wbr>security/sitelock.php</a> respectivel for more details.<br>
- Order a hosting package from 2GB or more and get a .com.ng FREE domain. Visit <a href="https://www.whogohost.com/hosting/shared-hosting.php" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.whogohost.com/hosting/shared-hosting.php&amp;source=gmail&amp;ust=1561259409804000&amp;usg=AFQjCNH9bre2mYPEAh5I0ktXcMEICgudAA">https://www.<span class="il">whogohost</span>.com/<wbr>hosting/shared-hosting.php</a> to see all our hosting packages at rock bottom prices</p><div class="yj6qo"></div><div class="adL">
</div></div>